export const STEP_F_DONE = "isStepFDone";
export const STEP_S_DONE = "isStepSDone";
export const STEP_T_DONE = "isStepTDone";
export const BACK_STEP = "isBack";
export const SUBMIT_STEP_LAST = "submitStepLast";

/**
 * v2.4 tuấn anh
 * Update dữ liệu trong form đăng ký bán thêm
 */
export const RESET_NAVIGATION_DATA				= "[EXTRA_SERVICE] RESET_NAVIGATION_DATA";
export const UPDATE_BACK_SCREEN_DETAIL			= "[EXTRA_SERVICE] UPDATE_BACK_SCREEN_DETAIL";
export const UPDATE_INFO_REGISTRATION			= '[EXTRA_SERVIVE_BOOKPORT] UPDATE_INFO_REGISTRATION';

/**
 * v2.7
 * Update dữ liệu bookport
 */
export const SAVE_INSTALL_ADDRESS				= '[EXTRA_SERVIVE_BOOKPORT] SAVE_INSTALL_ADDRESS';
export const PUSH_DATA_INFO_REGISTRATION		= '[EXTRA_SERVIVE_BOOKPORT] PUSH_DATA_INFO_REGISTRATION';

export const RESET_DATA_BOOKPORT            = '[EXTRA_SERVIVE_BOOKPORT] RESET_DATA_BOOKPORT';
export const RESET_ALL_DATA_BOOKPORT		= '[EXTRA_SERVIVE_BOOKPORT] RESET_ALL_DATA_BOOKPORT';
export const SAVE_LAT_LNG_DEVICED			= '[EXTRA_SERVIVE_BOOKPORT] SAVE_LAT_LNG_DEVICED';
export const CLEAR_CONTRACT_TEMP			= '[EXTRA_SERVIVE_BOOKPORT] CLEAR_CONTRACT_TEMP';

export const LOAD_MAP				= '[EXTRA_SERVIVE_BOOKPORT] LOAD_MAP';
export const DRAG_MAP				= '[EXTRA_SERVIVE_BOOKPORT] DRAG_MAP';
export const CHANGE_POINT_GROUP		= '[EXTRA_SERVIVE_BOOKPORT] CHANGE_POINT_GROUP';
export const CLEAR_DATA_MAP			= '[EXTRA_SERVIVE_BOOKPORT] CLEAR_DATA_MAP';
export const CHANGE_NETWORK_TYPE	= '[EXTRA_SERVIVE_BOOKPORT] CHANGE_NETWORK_TYPE';
export const LOADING				= '[EXTRA_SERVIVE_BOOKPORT] LOADING';
export const GENERATION_ADDRESS		= '[EXTRA_SERVIVE_BOOKPORT] GENERATION_ADDRESS';
export const SHOW_POINT_GROUP		= '[EXTRA_SERVIVE_BOOKPORT] SHOW_POINT_GROUP';
export const CHANGE_TYPE_BOOK_PORT	= '[EXTRA_SERVIVE_BOOKPORT] CHANGE_TYPE_BOOK_PORT';
export const CHANGE_TYPE_NOTIFY		= '[EXTRA_SERVIVE_BOOKPORT] CHANGE_TYPE_NOTIFY';
export const ALLOW_BOOKPORT			= '[EXTRA_SERVIVE_BOOKPORT] ALLOW_BOOKPORT';
export const REGION_BOOK_PORT		= '[EXTRA_SERVIVE_BOOKPORT] REGION_BOOK_PORT';
export const IS_MAP_READY			= '[EXTRA_SERVIVE_BOOKPORT] IS_MAP_READY';